# heart_rate_sentinel_server

The time somehow seems to be in Greenwich Mean Time. The actual number date and time is correct with our time zone but it is followed by GMT, so Python somehow thinks I am in that time zone. I'm not sure how to fix this, but I don't think it's a big deal, so I am leaving the times in GMT. 
